import { useMemo, useState } from "react";
import { ArrowUpRight, CalendarRange, TrendingUp } from "lucide-react";
import { Bar, CartesianGrid, ComposedChart, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import AppShell from "@/components/AppShell";
import { useFinanceStore } from "@/hooks/useFinanceStore";
import { currentMonth, expenseTotals, expensesForMonth, formatCurrency, incomeForMonth } from "@/lib/finance";

export default function Annual() {
  const { data } = useFinanceStore();
  const thisYear = Number(currentMonth().slice(0, 4));
  const [year, setYear] = useState(thisYear);
  const months = useMemo(() => Array.from({ length: 12 }, (_, index) => `${year}-${String(index + 1).padStart(2, "0")}`), [year]);
  const monthly = useMemo(() => months.map((month) => { const expenses = expensesForMonth(data, month); const expenseTotal = expenseTotals(expenses); return { month, label: new Intl.DateTimeFormat("pt-BR", { month: "short" }).format(new Date(Number(month.slice(0, 4)), Number(month.slice(5, 7)) - 1, 1)).replace(".", ""), Receitas: incomeForMonth(data, month), Despesas: expenseTotal.total, Essencial: expenseTotal.essential }; }), [data, months]);
  const categories = useMemo(() => Array.from(new Set([...data.transactions.filter((item) => item.type === "expense").map((item) => item.category), ...data.installments.map((item) => item.category)])).sort(), [data]);
  const averageEssential = monthly.reduce((sum, item) => sum + item.Essencial, 0) / 12;
  const matrixValue = (category: string, month: string) => expensesForMonth(data, month).filter((item) => item.category === category).reduce((sum, item) => sum + item.amount, 0);

  return <AppShell><div className="animate-[page-in_400ms_ease-out]" data-testid="annual-dashboard-page">
    <header className="mb-8 flex flex-col justify-between gap-5 border-b border-slate-800/80 pb-7 sm:flex-row sm:items-end" data-testid="annual-header"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-cyan-500">Panorama · {year}</p><h1 className="font-heading text-3xl font-semibold tracking-tight text-slate-50" data-testid="annual-title">O ano em uma leitura.</h1><p className="mt-3 max-w-xl text-sm leading-relaxed text-slate-400" data-testid="annual-description">Encontre ritmos, sazonalidades e o custo real de manter a sua vida funcionando.</p></div><label className="flex items-center gap-3" data-testid="year-selector-label"><span className="text-xs uppercase tracking-[0.14em] text-slate-500">Ano</span><select value={year} onChange={(event) => setYear(Number(event.target.value))} className="h-9 rounded-lg border border-slate-700 bg-slate-900 px-3 text-sm font-medium text-slate-100 outline-none transition-colors duration-200 focus:border-cyan-700" data-testid="year-selector"><option value={thisYear}>{thisYear}</option><option value={thisYear - 1}>{thisYear - 1}</option><option value={thisYear + 1}>{thisYear + 1}</option></select></label></header>
    <section className="grid gap-4 md:grid-cols-3" data-testid="annual-summary-cards"><div className="rounded-xl border border-slate-800 bg-slate-900/85 p-5" data-testid="annual-income-card"><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-[0.14em] text-slate-500">Receitas no ano</span><ArrowUpRight size={17} className="text-emerald-400" /></div><p className="mt-5 font-heading text-2xl font-semibold text-slate-50" data-testid="annual-income-value">{formatCurrency(monthly.reduce((sum, item) => sum + item.Receitas, 0))}</p><p className="mt-1 text-xs text-slate-500">Somatório dos 12 meses</p></div><div className="rounded-xl border border-slate-800 bg-slate-900/85 p-5" data-testid="annual-expense-card"><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-[0.14em] text-slate-500">Despesas no ano</span><TrendingUp size={17} className="text-cyan-400" /></div><p className="mt-5 font-heading text-2xl font-semibold text-slate-50" data-testid="annual-expense-value">{formatCurrency(monthly.reduce((sum, item) => sum + item.Despesas, 0))}</p><p className="mt-1 text-xs text-slate-500">À vista + parcelas</p></div><div className="rounded-xl border border-slate-800 bg-slate-900/85 p-5" data-testid="annual-essential-card"><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-[0.14em] text-slate-500">Média essencial</span><CalendarRange size={17} className="text-amber-400" /></div><p className="mt-5 font-heading text-2xl font-semibold text-slate-50" data-testid="annual-average-value">{formatCurrency(averageEssential)}</p><p className="mt-1 text-xs text-slate-500">Média anual de sobrevivência</p></div></section>

    <section className="mt-6" data-testid="annual-matrix-section"><Card className="border-slate-800 bg-slate-900/85" data-testid="annual-matrix-card"><CardHeader className="border-b border-slate-800/80"><CardTitle className="font-heading text-lg text-slate-100">Matriz de categorias</CardTitle><p className="mt-1 text-sm text-slate-500">Despesas consolidadas por categoria e competência</p></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="min-w-[980px] w-full text-left text-sm" data-testid="annual-matrix-table"><thead className="border-b border-slate-800 text-xs uppercase tracking-wider text-slate-500"><tr><th className="sticky left-0 bg-slate-900 px-5 py-3 font-medium">Categoria</th>{monthly.map((item) => <th key={item.month} className="px-3 py-3 text-right font-medium">{item.label}</th>)}</tr></thead><tbody className="divide-y divide-slate-800/80">{categories.map((category) => <tr key={category} className="transition-colors duration-200 hover:bg-slate-800/30" data-testid={`annual-category-row-${category.toLowerCase().replaceAll(" ", "-")}`}><td className="sticky left-0 bg-slate-900 px-5 py-3 font-medium text-slate-300">{category}</td>{months.map((month) => <td key={month} className="px-3 py-3 text-right font-heading text-xs text-slate-400" data-testid={`annual-cell-${category.toLowerCase().replaceAll(" ", "-")}-${month}`}>{formatCurrency(matrixValue(category, month)).replace("R$", "")}</td>)}</tr>)}{categories.length === 0 && <tr><td colSpan={13} className="px-5 py-10 text-center text-slate-500" data-testid="annual-matrix-empty-state">Cadastre despesas para preencher a matriz.</td></tr>}</tbody></table></div></CardContent></Card></section>

    <section className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]" data-testid="annual-charts-section"><Card className="border-slate-800 bg-slate-900/85" data-testid="annual-cashflow-card"><CardHeader><CardTitle className="font-heading text-base text-slate-100">Fluxo de caixa</CardTitle><p className="text-sm text-slate-500">Receitas e despesas ao longo do ano</p></CardHeader><CardContent><div className="h-72" data-testid="annual-cashflow-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={monthly} margin={{ top: 10, right: 12, left: -12, bottom: 0 }}><CartesianGrid stroke="#1e293b" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" stroke="#64748b" tickLine={false} axisLine={false} /><YAxis stroke="#64748b" tickLine={false} axisLine={false} tickFormatter={(value) => `R$${Number(value) / 1000}k`} /><Tooltip contentStyle={{ background: "#0f172a", border: "1px solid #334155", borderRadius: 8, color: "#e2e8f0" }} /><Legend /><Line type="monotone" dataKey="Receitas" stroke="#34d399" strokeWidth={2} dot={{ r: 3, fill: "#34d399" }} animationDuration={800} /><Line type="monotone" dataKey="Despesas" stroke="#22d3ee" strokeWidth={2} dot={{ r: 3, fill: "#22d3ee" }} animationDuration={800} /></LineChart></ResponsiveContainer></div></CardContent></Card><Card className="border-slate-800 bg-slate-900/85" data-testid="annual-essential-chart-card"><CardHeader><CardTitle className="font-heading text-base text-slate-100">Custo essencial mensal</CardTitle><p className="text-sm text-slate-500">A linha marca a média anual de {formatCurrency(averageEssential)}</p></CardHeader><CardContent><div className="h-72" data-testid="annual-essential-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={monthly} margin={{ top: 10, right: 12, left: -12, bottom: 0 }}><CartesianGrid stroke="#1e293b" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" stroke="#64748b" tickLine={false} axisLine={false} /><YAxis stroke="#64748b" tickLine={false} axisLine={false} tickFormatter={(value) => `R$${Number(value) / 1000}k`} /><Tooltip contentStyle={{ background: "#0f172a", border: "1px solid #334155", borderRadius: 8, color: "#e2e8f0" }} /><Bar dataKey="Essencial" name="Custo essencial" fill="#0e7490" radius={[4, 4, 0, 0]} animationDuration={700} /><Line type="monotone" dataKey={() => averageEssential} name="Média anual" stroke="#f59e0b" strokeWidth={2} dot={false} animationDuration={700} /></ComposedChart></ResponsiveContainer></div></CardContent></Card></section>
  </div></AppShell>;
}
