import { useMemo, useState } from "react";
import { ArrowUpRight, CreditCard as CreditCardIcon, Gauge, ShieldCheck } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import AppShell from "@/components/AppShell";
import MonthSelect from "@/components/MonthSelect";
import { useFinanceStore } from "@/hooks/useFinanceStore";
import { currentMonth, expensesForMonth, formatCurrency, monthLabel } from "@/lib/finance";

const palette = ["#22d3ee", "#38bdf8", "#0e7490", "#64748b", "#f59e0b"];

export default function Cards() {
  const { data } = useFinanceStore();
  const [month, setMonth] = useState(currentMonth());
  const expenses = useMemo(() => expensesForMonth(data, month).filter((item) => item.paymentMethod === "credit"), [data, month]);
  const invoices = useMemo(() => data.cards.map((card) => ({ ...card, consumed: expenses.filter((item) => item.cardId === card.id).reduce((sum, item) => sum + item.amount, 0) })), [data.cards, expenses]);
  const totalConsumed = invoices.reduce((sum, item) => sum + item.consumed, 0);
  const pieData = invoices.filter((item) => item.consumed > 0).map((item) => ({ name: item.name, value: item.consumed }));

  return <AppShell><div className="animate-[page-in_400ms_ease-out]" data-testid="cards-dashboard-page">
    <header className="mb-8 flex flex-col justify-between gap-5 border-b border-slate-800/80 pb-7 sm:flex-row sm:items-end" data-testid="cards-header"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-cyan-500">Controle de crédito · {monthLabel(month)}</p><h1 className="font-heading text-3xl font-semibold tracking-tight text-slate-50" data-testid="cards-title">Seu crédito, sob controle.</h1><p className="mt-3 max-w-xl text-sm leading-relaxed text-slate-400" data-testid="cards-description">Veja o comprometimento de cada cartão sem perder de vista o limite disponível.</p></div><MonthSelect value={month} onChange={setMonth} /></header>
    <section className="grid gap-4 md:grid-cols-3" data-testid="credit-summary-cards"><div className="rounded-xl border border-slate-800 bg-slate-900/85 p-5 transition-transform duration-200 hover:-translate-y-0.5 hover:border-slate-700" data-testid="credit-total-limit-card"><div className="flex items-start justify-between"><span className="text-xs font-medium uppercase tracking-[0.14em] text-slate-500">Limite total</span><span className="flex size-9 items-center justify-center rounded-lg bg-slate-800 text-cyan-400"><CreditCardIcon size={17} /></span></div><p className="mt-5 font-heading text-2xl font-semibold text-slate-50" data-testid="credit-total-limit-value">{formatCurrency(invoices.reduce((sum, item) => sum + item.limit, 0))}</p><p className="mt-1 text-xs text-slate-500">{data.cards.length} cartões cadastrados</p></div><div className="rounded-xl border border-slate-800 bg-slate-900/85 p-5 transition-transform duration-200 hover:-translate-y-0.5 hover:border-slate-700" data-testid="credit-invoice-total-card"><div className="flex items-start justify-between"><span className="text-xs font-medium uppercase tracking-[0.14em] text-slate-500">Fatura do mês</span><span className="flex size-9 items-center justify-center rounded-lg bg-cyan-950/60 text-cyan-400"><ArrowUpRight size={17} /></span></div><p className="mt-5 font-heading text-2xl font-semibold text-slate-50" data-testid="credit-invoice-total-value">{formatCurrency(totalConsumed)}</p><p className="mt-1 text-xs text-slate-500">Compras à vista + parcelas</p></div><div className="rounded-xl border border-slate-800 bg-slate-900/85 p-5 transition-transform duration-200 hover:-translate-y-0.5 hover:border-slate-700" data-testid="credit-available-total-card"><div className="flex items-start justify-between"><span className="text-xs font-medium uppercase tracking-[0.14em] text-slate-500">Limite disponível</span><span className="flex size-9 items-center justify-center rounded-lg bg-emerald-950/50 text-emerald-400"><ShieldCheck size={17} /></span></div><p className="mt-5 font-heading text-2xl font-semibold text-slate-50" data-testid="credit-available-total-value">{formatCurrency(invoices.reduce((sum, item) => sum + Math.max(item.limit - item.consumed, 0), 0))}</p><p className="mt-1 text-xs text-slate-500">Após a fatura estimada</p></div></section>

    <section className="mt-6" data-testid="invoice-table-section"><Card className="border-slate-800 bg-slate-900/85" data-testid="invoice-table-card"><CardHeader className="border-b border-slate-800/80"><div className="flex items-center justify-between"><div><CardTitle className="font-heading text-lg text-slate-100">Faturas por cartão</CardTitle><p className="mt-1 text-sm text-slate-500">Ciclo de {monthLabel(month)} · fechamento aplicado automaticamente</p></div><Badge variant="outline" className="border-cyan-800/60 bg-cyan-950/30 text-cyan-300" data-testid="billing-rule-badge">Regra de fechamento ativa</Badge></div></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-left text-sm" data-testid="invoice-table"><thead className="border-b border-slate-800 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3 font-medium">Cartão</th><th className="px-5 py-3 text-right font-medium">Limite total</th><th className="px-5 py-3 text-right font-medium">Fatura estimada</th><th className="px-5 py-3 text-right font-medium">Disponível</th><th className="px-5 py-3 text-right font-medium">Uso</th></tr></thead><tbody className="divide-y divide-slate-800/80">{invoices.map((item) => { const usage = item.limit ? (item.consumed / item.limit) * 100 : 0; return <tr key={item.id} className="transition-colors duration-200 hover:bg-slate-800/30" data-testid={`invoice-row-${item.id}`}><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-lg bg-slate-800 text-cyan-400"><CreditCardIcon size={15} /></span><div><p className="font-medium text-slate-200">{item.name}</p><p className="mt-1 text-xs text-slate-600">Fecha dia {item.closingDay} · vence dia {item.dueDay}</p></div></div></td><td className="px-5 py-4 text-right font-heading text-slate-300">{formatCurrency(item.limit)}</td><td className="px-5 py-4 text-right font-heading font-semibold text-cyan-300">{formatCurrency(item.consumed)}</td><td className="px-5 py-4 text-right font-heading text-slate-300">{formatCurrency(Math.max(item.limit - item.consumed, 0))}</td><td className="min-w-36 px-5 py-4 text-right"><div className="mb-1 text-xs text-slate-400">{usage.toFixed(1)}%</div><div className="ml-auto h-1.5 max-w-24 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full ${usage > 80 ? "bg-rose-400" : usage > 50 ? "bg-amber-400" : "bg-cyan-400"}`} style={{ width: `${Math.min(usage, 100)}%` }} /></div></td></tr>; })}{invoices.length === 0 && <tr><td colSpan={5} className="px-5 py-12 text-center text-slate-500" data-testid="cards-empty-state">Cadastre seu primeiro cartão na área de Lançamentos.</td></tr>}</tbody></table></div></CardContent></Card></section>

    <section className="mt-6 grid gap-6 lg:grid-cols-[0.8fr_1.2fr]" data-testid="credit-charts-section"><Card className="border-slate-800 bg-slate-900/85" data-testid="invoice-distribution-card"><CardHeader><CardTitle className="font-heading text-base text-slate-100">Distribuição da fatura</CardTitle><p className="text-sm text-slate-500">Quem consome mais crédito</p></CardHeader><CardContent><div className="h-64" data-testid="invoice-distribution-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pieData} dataKey="value" nameKey="name" innerRadius={62} outerRadius={90} paddingAngle={3} animationDuration={800}>{pieData.map((item, index) => <Cell key={item.name} fill={palette[index % palette.length]} />)}</Pie><Tooltip contentStyle={{ background: "#0f172a", border: "1px solid #334155", borderRadius: 8, color: "#e2e8f0" }} /><Legend wrapperStyle={{ fontSize: 11, color: "#94a3b8" }} /></PieChart></ResponsiveContainer></div></CardContent></Card><Card className="border-slate-800 bg-slate-900/85" data-testid="limit-comparison-card"><CardHeader><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-slate-800 text-cyan-400"><Gauge size={17} /></span><div><CardTitle className="font-heading text-base text-slate-100">Comprometimento de limite</CardTitle><p className="text-sm text-slate-500">Limite total comparado à fatura atual</p></div></div></CardHeader><CardContent><div className="h-64" data-testid="limit-comparison-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={invoices} margin={{ top: 8, right: 12, left: -12, bottom: 0 }}><CartesianGrid stroke="#1e293b" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" stroke="#64748b" tickLine={false} axisLine={false} /><YAxis stroke="#64748b" tickLine={false} axisLine={false} tickFormatter={(value) => `R$${Number(value) / 1000}k`} /><Tooltip contentStyle={{ background: "#0f172a", border: "1px solid #334155", borderRadius: 8, color: "#e2e8f0" }} /><Legend /><Bar dataKey="limit" name="Limite total" fill="#475569" radius={[4, 4, 0, 0]} animationDuration={700} /><Bar dataKey="consumed" name="Fatura do mês" fill="#22d3ee" radius={[4, 4, 0, 0]} animationDuration={700} /></BarChart></ResponsiveContainer></div></CardContent></Card></section>
  </div></AppShell>;
}
